"""Compatibility facade for private isometric edge helpers."""

from ._svg_iso_edge_draw import _iso_edge_path as _iso_edge_path
from ._svg_iso_edge_draw import _iso_front_anchor as _iso_front_anchor
from ._svg_iso_edge_draw import _render_iso_edges as _render_iso_edges
from ._svg_iso_edge_draw import _render_iso_poe_icon as _render_iso_poe_icon
from ._svg_iso_edge_draw import _render_iso_standard_edge as _render_iso_standard_edge
from ._svg_iso_edge_draw import _render_iso_vlan_striped_edge as _render_iso_vlan_striped_edge
from ._svg_iso_edge_draw import _render_single_iso_edge as _render_single_iso_edge
from ._svg_iso_edge_draw import _resolve_edge_coords as _resolve_edge_coords
from ._svg_iso_edge_labels import _iso_client_attachment as _iso_client_attachment
from ._svg_iso_edge_labels import _record_iso_client_edge_label as _record_iso_client_edge_label
from ._svg_iso_edge_labels import _record_iso_device_edge_label as _record_iso_device_edge_label
from ._svg_iso_edge_labels import _record_iso_edge_label as _record_iso_edge_label
